### ISSUE TITLE
Cummulative matrix transformation (translate, rotate) from OpenSCAD

### ISSUE THREAD

**Issue by dimitre** [colah/ImplicitCAD#220] opened 2019-05-03 00:08 UTC
I know the project isn't meant to be 100% compatible with OpenSCAD but I've noticed a very basic issue trying to run the following code in both of them
```c++
union() {
    cube(size=[10,20,5]);
    rotate(30)
    translate([0,30,0]) 
    {
        cube(size=[10,20,5]);
        rotate(30)
        translate([0,30,0]) 
        {
            cube(size=[10,20,5]);
        }
    }
}
```
and ImplicitCAD doens't seem to understand the cumulative translation and rotation
![Screen Shot 2019-05-02 at 21 08 05](https://user-images.githubusercontent.com/58289/57114183-660bb300-6d1e-11e9-889c-8d7dd2150189.png)

**Comment by l29ah** [comment] 2019-06-29 00:32
The result suggests that there's some problem with a bounding box calculation.

**Comment by l29ah** [comment] 2019-06-29 00:51
Minimal reproducer: `rotate(30) cube(10);`.

**Comment by julialongtin** [comment] 2019-07-09 12:59
Reproduced with the original code. investigating.

**Comment by isovector** [comment] 2020-11-26 20:56
I'm unable to reproduce in the Haskell library:

```haskell

main :: IO ()
main = writeSTL 1 "/tmp/yo.stl" $
  let cube = cubeR 0 True (10, 20, 5)
   in union
        [ cube
        , rotate3 (degZ 30) $ translate (0, 30, 0) $ union
          [ cube
          , rotate3 (degZ 30) $ translate (0, 30, 0) cube
          ]
        ]
```

produces:

![2020-11-26-125611_427x322_scrot](https://user-images.githubusercontent.com/307223/100390933-d22bc700-2fe6-11eb-9554-73824ddc4f1f.png)

**Comment by julialongtin** [comment] 2021-02-28 14:12
Fixed. Closing.

**Closed by julialongtin** 2021-02-28 14:12 UTC
Labels: graphics-engine
