### ISSUE TITLE
implicit unions are missing in several of places

### ISSUE THREAD

**Issue by tolomea** [colah/ImplicitCAD#30] opened 2012-03-03 23:24 UTC
In openscad transform modules union their arguments, as does the top level. So these all produce 2 spheres in penscad while in implicitcad they only produce 1 sphere, in all cases of size one, for the first two cases because that one was first, in the third case the difference of the first and second which is the first since they are non intersecting.

sphere(1);
translate([10,10,10]) sphere(2);

translate([0,0,0]){
    sphere(1);
    translate([10,10,10]) sphere(2);
}

difference(){
    translate([0,0,0]){
        sphere(1);
        translate([10,10,10]) sphere(2);
    }
}

**Comment by julialongtin** [comment] 2016-11-20 20:23
I'm good with leaving this intentional change in. philosophy of least surprise, and all that.

**Comment by julialongtin** [comment] 2017-03-11 05:46
Closing issue. Feature, not a bug. :)

**Closed** 2017-03-11 05:45 UTC
Labels: extopenscad
